package ProcesarDatosEstudiantes;


import javax.swing.JOptionPane;
/**
 *
 * @author Walla Peguero
 */
public class CapturarDatos extends javax.swing.JFrame {
    private String Nombre;
    private String Apellido;
    private String Matricula;
    private String Correo;
   
    /**
     * Creates new form CapturarDatos
     */
    public CapturarDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlCabecera = new javax.swing.JPanel();
        TextTitulo = new javax.swing.JLabel();
        PnlCuerpo = new javax.swing.JPanel();
        TextNombre = new javax.swing.JTextField();
        TextApellido = new javax.swing.JTextField();
        TextMatricula = new javax.swing.JTextField();
        TextCorreo = new javax.swing.JTextField();
        BtnCapturarDatos = new javax.swing.JButton();
        BtnPresentarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlCabecera.setBackground(new java.awt.Color(0, 122, 204));
        PnlCabecera.setForeground(new java.awt.Color(51, 0, 204));
        PnlCabecera.setToolTipText("");
        PnlCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextTitulo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        TextTitulo.setForeground(new java.awt.Color(255, 255, 255));
        TextTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTitulo.setText("Ingrese sus Datos ");
        PnlCabecera.add(TextTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 220, 60));

        getContentPane().add(PnlCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 60));

        PnlCuerpo.setBackground(new java.awt.Color(15, 15, 15));
        PnlCuerpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextNombre.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        TextNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre:"));
        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        PnlCuerpo.add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 210, 70));

        TextApellido.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        TextApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextApellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido:"));
        TextApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextApellidoActionPerformed(evt);
            }
        });
        PnlCuerpo.add(TextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, 70));

        TextMatricula.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        TextMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextMatricula.setBorder(javax.swing.BorderFactory.createTitledBorder("Matricula:"));
        TextMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMatriculaActionPerformed(evt);
            }
        });
        PnlCuerpo.add(TextMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 210, 70));

        TextCorreo.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        TextCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo:"));
        TextCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCorreoActionPerformed(evt);
            }
        });
        PnlCuerpo.add(TextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 210, 70));

        BtnCapturarDatos.setText("CapturarDatos");
        BtnCapturarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCapturarDatosActionPerformed(evt);
            }
        });
        PnlCuerpo.add(BtnCapturarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 130, 50));

        BtnPresentarDatos.setText("PresentarDatos");
        BtnPresentarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPresentarDatosActionPerformed(evt);
            }
        });
        PnlCuerpo.add(BtnPresentarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 150, 50));

        getContentPane().add(PnlCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 510, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextApellidoActionPerformed

    private void TextMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMatriculaActionPerformed

    private void TextCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCorreoActionPerformed

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

       private void limpiarCampos(){
        TextNombre.setText("");
        TextApellido.setText("");
        TextMatricula.setText("");
        TextCorreo.setText("");
        TextNombre.requestFocus();
    }
    private void BtnCapturarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCapturarDatosActionPerformed
        this.Nombre = TextNombre.getText();
        this.Apellido = TextApellido.getText();
        this.Matricula =TextMatricula.getText();
        this.Correo = TextCorreo.getText();
        JOptionPane.showMessageDialog(null, "Datos Cargados Exitosamente!!!"); 
        limpiarCampos();
    }//GEN-LAST:event_BtnCapturarDatosActionPerformed
       
    private void BtnPresentarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPresentarDatosActionPerformed
        PresentarDatos presentar = new PresentarDatos();
        presentar.mostrar(Nombre, Apellido, Matricula, Correo);
        presentar.setLocationRelativeTo(null);
        presentar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPresentarDatosActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapturarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapturarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapturarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapturarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapturarDatos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCapturarDatos;
    private javax.swing.JButton BtnPresentarDatos;
    private javax.swing.JPanel PnlCabecera;
    private javax.swing.JPanel PnlCuerpo;
    private javax.swing.JTextField TextApellido;
    private javax.swing.JTextField TextCorreo;
    private javax.swing.JTextField TextMatricula;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JLabel TextTitulo;
    // End of variables declaration//GEN-END:variables

}
