package ProcesarDatosEstudiantes;

/**
 *
 * @author Walla Peguero
 */
public class PresentarDatos extends javax.swing.JFrame {
    /**
     * Creates new form PresentarDatos
     */
    public PresentarDatos() {
        initComponents();
    }
    
    public void mostrar(String Nombre, String Apellido, String Matricula, String Correo)
    {
        TextNombreP.setText(Nombre);
        TextApellidoP.setText(Apellido);
        TextMatriculaP.setText(Matricula);
        TextCorreoP.setText(Correo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TextCorreoP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextNombreP = new javax.swing.JLabel();
        TextApellidoP = new javax.swing.JLabel();
        TextMatriculaP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 122, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Presentar Datos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 190, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 100));

        jPanel2.setBackground(new java.awt.Color(15, 15, 15));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Correo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 80, 40));

        TextCorreoP.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        TextCorreoP.setForeground(new java.awt.Color(255, 255, 255));
        TextCorreoP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextCorreoP.setText("jLabel2");
        jPanel2.add(TextCorreoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 270, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nombre:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Apellido:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Matricula:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, 40));

        TextNombreP.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        TextNombreP.setForeground(new java.awt.Color(255, 255, 255));
        TextNombreP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextNombreP.setText("jLabel2");
        jPanel2.add(TextNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 220, 50));

        TextApellidoP.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        TextApellidoP.setForeground(new java.awt.Color(255, 255, 255));
        TextApellidoP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextApellidoP.setText("jLabel2");
        jPanel2.add(TextApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 220, 50));

        TextMatriculaP.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        TextMatriculaP.setForeground(new java.awt.Color(255, 255, 255));
        TextMatriculaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextMatriculaP.setText("jLabel2");
        jPanel2.add(TextMatriculaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 240, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 490, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresentarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresentarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresentarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresentarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PresentarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextApellidoP;
    private javax.swing.JLabel TextCorreoP;
    private javax.swing.JLabel TextMatriculaP;
    private javax.swing.JLabel TextNombreP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
